version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/bugtracker
      - SESSION_SECRET=your-secret-key-here
      - OPENAI_API_KEY=your-openai-key-here
      - STRIPE_SECRET_KEY=your-stripe-key-here
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./recordings:/app/recordings

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=bugtracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: